version: '3.4'

networks:
  monitoring_sea:

volumes:
  graphite_data: {}
  grafana_data: {}
  prometheus_data: {}
  loki_data: {}
  promtail_tmp: {}

configs:
  Prometheus:
    file: ./config/prometheus/prometheus.yml
  Prometheus_Web:
    file: ./config/prometheus/web-config.yml
  Grafana_Prometheus:
    file: ./config/grafana/provisioning/datasources/prometheus.yml
  Grafana_Loki:
    file: ./config/grafana/provisioning/datasources/loki.yml
  Promtail_config:
    file: ./config/promtail/promtail-config.yml
  Loki_config:
    file: ./config/loki/loki-config.yml
  Alertmanager:
    file: ./config/alertmanager/alertmanager.yml
  # Collectd:
  #   file: ./config/collectd/collectd.conf
  Mikrotik_devices:
    file: ./config/mikrotik-exporter/config.yml


services:
  grafana:
    image: grafana/grafana:8.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    configs:
      - source: Grafana_Prometheus
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: Grafana_Loki
        target: /etc/grafana/provisioning/datasources/loki.yml
    env_file:
      - ./config/grafana/grafana.config
    networks:
      - monitoring_sea
    ports:
      - 3111:3000
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  graphite:
    image: graphiteapp/graphite-statsd:latest
    volumes:
      - graphite_data:/opt/graphite/storage
    networks:
      - monitoring_sea
    ports:
      - 2003:2003
      #- 8081:8080
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:v2.26.0
    volumes:
      - prometheus_data:/prometheus
    configs:
      - source: Prometheus
        target: /etc/prometheus/prometheus.yml
      - source: Prometheus_Web
        target: /path/to/web-config.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=400h'
      - '--web.enable-lifecycle'
      - '--web.config.file=/path/to/web-config.yml'
    networks:
      - monitoring_sea
    ports:
      - 9090:9090
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  alertmanager:
    image: prom/alertmanager
    environment:
      - TZ=America/Belem
    configs:
      - source: Alertmanager
        target: /etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitoring_sea
    ports:
      - 9093:9093
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  blackbox:
    image: prom/blackbox-exporter
    networks:
      - monitoring_sea
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  fping:
    image: bbrks/fping-exporter:latest
    networks:
      - monitoring_sea
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  loki:
    image: grafana/loki:latest
    configs:
      - source: Loki_config
        target: /etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - monitoring_sea
    ports:
      - "3100:3100"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/promtail-config.yml
    configs:
      - source: Promtail_config
        target: /etc/promtail/promtail-config.yml
    volumes:
      - promtail_tmp:/tmp
    networks:
      - monitoring_sea
    ports:
      - 2514:1514
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  prom_mikrotik_exporter:
     image: hatamiarash7/mikrotik-exporter
     configs:
       - source: Mikrotik_devices
         target: /config/config.yml
     environment:
       - CONFIG_FILE=/config/config.yml
     networks:
       - monitoring_sea
     ports:
       - 9436:9436
     deploy:
       replicas: 1
       update_config:
         parallelism: 2
         delay: 10s
       restart_policy:
         condition: on-failure

