devices:
  - name: PA-CST-SERVICOS-CE
    address: 170.82.180.17
    user: madson.ramos
    password: teste

features:
  bgp: true
  conntrack: true
  dhcp: true
  dhcpv6: true
  dhcpl: true
  routes: true
  pools: true
  optics: true
  wlansta: true
  wlanif: true
  ipsec: true
  lte: true
  netwatch: true
