version: '3.3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    restart: unless-stopped
    ports:
      - "2000:2000"
    volumes:
      - ./node/servers.json:/usr/src/app/servers.json
